var floatAge, floatDays, intWeeks, floatMonths, intFortnights;
     floatAge = parseFloat(prompt("Enter Age"));
     floatDays = parseFloat(floatAge * 365.25).toFixed(2);
     intWeeks = parseInt(floatDays/7);
     floatMonths = parseFloat(floatAge * 12).toFixed(2);
     intFortnights = parseInt(floatDays/14);
     alert("Age in Years = " + floatAge);
     alert("Age in Days = " + floatDays);
     alert("Age in Weeks = " + intWeeks);
     alert("Age in Months = " + floatMonths);
     alert("Age in Fortnights = " + intFortnights);